// src/app/models/messaging-enums.ts

export enum ConversationType {
  LINE_ASSIGNMENT = 'LINE_ASSIGNMENT',
  VALIDATION_ASSIGNMENT = 'VALIDATION_ASSIGNMENT',
  DIRECT = 'DIRECT'
}

export enum MessageType {
  TEXT = 'TEXT',
  SYSTEM_NOTIFICATION = 'SYSTEM_NOTIFICATION',
  VALIDATION_ALERT = 'VALIDATION_ALERT',
  LINE_ASSIGNMENT = 'LINE_ASSIGNMENT',
  VALIDATION_ASSIGNMENT = 'VALIDATION_ASSIGNMENT'
}

export enum NotificationType {
  LINE_ASSIGNED = 'LINE_ASSIGNED',
  VALIDATION_ASSIGNED = 'VALIDATION_ASSIGNED',
  VALIDATION_CLOSED = 'VALIDATION_CLOSED',
  AI_ALERT = 'AI_ALERT',
  NEW_MESSAGE = 'NEW_MESSAGE',
  SYSTEM = 'SYSTEM',
  MESSAGE = 'MESSAGE',
  ASSIGNMENT = 'ASSIGNMENT',
  VALIDATION_CREATED = 'VALIDATION_CREATED',
  // Ticket-specific notifications
  TICKET_ASSIGNMENT = 'TICKET_ASSIGNMENT',
  TICKET_STATUS_CHANGE = 'TICKET_STATUS_CHANGE',
  PREP_VALIDATED = 'PREP_VALIDATED',
  TICKET_REVIEW = 'TICKET_REVIEW',
  TICKET_CANCELLED = 'TICKET_CANCELLED'
}